version: "3.5"

services:
  udic-website:
    build: "."
    container_name: "udic-website"
    networks:
      - "service-bridge"
    restart: "always"

networks:
  service-bridge:
    external: true
